### ISSUE TITLE
Assignment 5 final touches

### ISSUE THREAD

**Issue by chasemcintyre105** [chasemcintyre105/cmRepository#16]
I have added a file 'ChaseMcintyreAssignment5' to the repository.
It currently satisfies points 1, 2, and 3 of assignment 12 completely. However, it does not completely satisfy point 4. I have added functionality allowing the skeleton to 'hit' the player, and the allowing the player to 'hit' the skeleton.
One more of the four listed features need to be added to complete the assignment. The remaining choices are: 1) attach dialogue to the character; start this dialogue when the player approaches, 2) regulate spawning, death and re-spawning.

**Comment by zeknock** [comment]
I'll do number 1(attach dialogue)! Thank you!

**Comment by JDMC93003** [comment]
I have made a Pawn, Rook, Bishop, Queen, and King for the game. however, I have tried to make a knight but it is a work in progress.

**Comment by JDMC93003** [comment]
I have made a Pawn, Rook, Bishop, Queen, and King for the game. however, I have tried to make a knight but it is a work in progress.

**Comment by JDMC93003** [comment]
I have made a Pawn, Rook, Bishop, Queen, and King for the game. however, I have tried to make a knight but it is a work in progress.

**Comment by chasemcintyre105** [comment]
Awesome! 
Have you painted them at all?
We also need to upload them into Unity, have you done this step?
If not, I can figure out how to properly upload them.
